version: "3"
services:
  app:
    image: node
    container_name: "app"
    command: bash -c "yarn && yarn start"
    working_dir: /webapp
    volumes:
      - ./webapp:/webapp
    ports:
      - "3000:3000"
  
  api: 
    image: node
    container_name: "api"
    command: bash -c "npm install  && npm run createTestDb && npm run migration:run && npm run migrationTest:run && npm start"
    working_dir: /api
    volumes:
      - ./api:/api
    ports:
      - "4201:4201"
    environment:
      - DB_HOST=db
      - DB_NAME=slackMeHarder
      - DB_TEST_NAME=test
    depends_on: 
      - db
  
  graph: 
    image: node
    container_name: "graph"
    command: bash -c "npm i && npm start"
    working_dir: /graphql
    volumes:
      - ./graphql:/graphql
    ports:
      - "4000:4000"
    environment:
      - API_HOST=api
      - API_USER_HOST=apiUsers
    depends_on: 
      - api
 
  db:
    image: "postgres"
    container_name: "db"
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=dokoliday
      - POSTGRES_DB=slackMeHarder
    ports:
      - "5432:5432"

  apiUsers: 
    image: node
    container_name: "apiUsers"
    command: bash -c "npm install && npm start"
    working_dir: /apiUsers
    volumes:
      - ./apiUsers:/apiUsers
    ports:
      - "5201:5201"
    environment:
      - DB_HOST=mongodb
      - DB_NAME=slackMeHarder
      - DB_TEST_NAME=test
    depends_on: 
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
        MONGO_INITDB_ROOT_USERNAME: alex
        MONGO_INITDB_ROOT_PASSWORD: dokoliday
    ports:
        - "27017:27017"
    
