 version: 2
 jobs:
   build:
     docker:
       - image: node
     steps:
       - checkout
       - run: 
          name:  installation des dependanses pour api
          command: cd api && npm install
       - run: ls
       - run: npm run test:ci
         

      


            